-- MySQL Script generated by MySQL Workbench
-- Wed Oct  7 16:28:05 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema labficat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema labficat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `labficat` DEFAULT CHARACTER SET utf8mb4 ;
USE `labficat` ;

-- -----------------------------------------------------
-- Table `labficat`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol`),
  UNIQUE INDEX `uq_rol_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`tipologia_poblacional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`tipologia_poblacional` (
  `id_tipologia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_tipologia`),
  UNIQUE INDEX `uq_tipologia_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`tipo_muestra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`tipo_muestra` (
  `id_tipo_muestra` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado_fisico` ENUM('SOLIDO', 'LIQUIDO') NOT NULL,
  PRIMARY KEY (`id_tipo_muestra`),
  UNIQUE INDEX `uq_tipo_muestra_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`parametro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`parametro` (
  `id_parametro` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `unidad_medida` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_parametro`),
  UNIQUE INDEX `uq_parametro_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`analisis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`analisis` (
  `id_analisis` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  `tarifa_externo` DECIMAL(11,2) NOT NULL DEFAULT 15000.00,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_analisis`),
  UNIQUE INDEX `uq_analisis_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`analisis_parametro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`analisis_parametro` (
  `id_analisis` INT NOT NULL,
  `id_parametro` INT NOT NULL,
  PRIMARY KEY (`id_analisis`, `id_parametro`),
  INDEX `idx_analisis_parametro_parametro` (`id_parametro` ASC) VISIBLE,
  CONSTRAINT `fk_analisis_parametro_analisis`
    FOREIGN KEY (`id_analisis`)
    REFERENCES `labficat`.`analisis` (`id_analisis`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_analisis_parametro_parametro`
    FOREIGN KEY (`id_parametro`)
    REFERENCES `labficat`.`parametro` (`id_parametro`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`analisis_tipo_muestra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`analisis_tipo_muestra` (
  `id_tipo_muestra` INT NOT NULL,
  `id_analisis` INT NOT NULL,
  PRIMARY KEY (`id_tipo_muestra`, `id_analisis`),
  INDEX `idx_analisis_tipo_muestra_analisis` (`id_analisis` ASC) VISIBLE,
  CONSTRAINT `fk_analisis_tipo_muestra_tipo`
    FOREIGN KEY (`id_tipo_muestra`)
    REFERENCES `labficat`.`tipo_muestra` (`id_tipo_muestra`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_analisis_tipo_muestra_analisis`
    FOREIGN KEY (`id_analisis`)
    REFERENCES `labficat`.`analisis` (`id_analisis`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`etapa_proceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`etapa_proceso` (
  `id_etapa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `orden` INT NOT NULL,
  PRIMARY KEY (`id_etapa`),
  UNIQUE INDEX `uq_etapa_nombre` (`nombre` ASC) VISIBLE,
  UNIQUE INDEX `uq_etapa_orden` (`orden` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`estado_solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`estado_solicitud` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_estado`),
  UNIQUE INDEX `uq_estado_solicitud_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`configuracion_sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`configuracion_sistema` (
  `clave` VARCHAR(60) NOT NULL,
  `valor` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`clave`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_rol` INT NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `tipo_documento` VARCHAR(20) NOT NULL,
  `numero_documento` VARCHAR(15) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `contrasena_hash` VARCHAR(255) NULL DEFAULT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `uq_usuario_documento` (`numero_documento` ASC) VISIBLE,
  UNIQUE INDEX `uq_usuario_correo` (`correo` ASC) VISIBLE,
  INDEX `idx_usuario_rol` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `labficat`.`rol` (`id_rol`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_tipologia` INT NULL DEFAULT NULL,
  `tipo_cliente` ENUM('INTERNO', 'EXTERNO') NOT NULL,
  `telefono` VARCHAR(10) NULL DEFAULT NULL,
  `razon_social` VARCHAR(100) NULL DEFAULT NULL,
  `nit` VARCHAR(20) NULL DEFAULT NULL,
  `acepta_tratamiento_datos_terminos_condiciones` TINYINT(1) NOT NULL DEFAULT 0,
  `fecha_aceptacion_datos` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `uq_cliente_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `idx_cliente_tipologia` (`id_tipologia` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `labficat`.`usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_cliente_tipologia`
    FOREIGN KEY (`id_tipologia`)
    REFERENCES `labficat`.`tipologia_poblacional` (`id_tipologia`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`token_recuperacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`token_recuperacion` (
  `id_token` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `token_hash` VARCHAR(255) NOT NULL,
  `fecha_expiracion` DATETIME NOT NULL,
  `usado` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_token`),
  INDEX `idx_token_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_token_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `labficat`.`usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`auditoria_acceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`auditoria_acceso` (
  `id_auditoria` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `ip` VARCHAR(45) NULL DEFAULT NULL,
  `accion` VARCHAR(60) NOT NULL,
  `fecha_hora` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_auditoria`),
  INDEX `idx_auditoria_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_auditoria_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `labficat`.`usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`solicitud` (
  `id_solicitud` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_estado` INT NOT NULL,
  `descripcion_inicial` VARCHAR(200) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_cierre` DATETIME NULL DEFAULT NULL,
  `motivo_desistimiento` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id_solicitud`),
  INDEX `idx_solicitud_cliente` (`id_cliente` ASC) VISIBLE,
  INDEX `idx_solicitud_estado` (`id_estado` ASC) VISIBLE,
  CONSTRAINT `fk_solicitud_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `labficat`.`cliente` (`id_cliente`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_solicitud_estado`
    FOREIGN KEY (`id_estado`)
    REFERENCES `labficat`.`estado_solicitud` (`id_estado`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`solicitud_analisis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`solicitud_analisis` (
  `id_solicitud` INT NOT NULL,
  `id_analisis` INT NOT NULL,
  PRIMARY KEY (`id_solicitud`, `id_analisis`),
  INDEX `idx_solicitud_analisis_analisis` (`id_analisis` ASC) VISIBLE,
  CONSTRAINT `fk_solicitud_analisis_solicitud`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `labficat`.`solicitud` (`id_solicitud`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_solicitud_analisis_analisis`
    FOREIGN KEY (`id_analisis`)
    REFERENCES `labficat`.`analisis` (`id_analisis`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`historial_estado_solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`historial_estado_solicitud` (
  `id_historial` BIGINT NOT NULL AUTO_INCREMENT,
  `id_solicitud` INT NOT NULL,
  `id_estado` INT NOT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  `fecha_hora` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `observacion` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id_historial`),
  INDEX `idx_hes_solicitud` (`id_solicitud` ASC) VISIBLE,
  INDEX `idx_hes_estado` (`id_estado` ASC) VISIBLE,
  INDEX `idx_hes_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_hes_solicitud`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `labficat`.`solicitud` (`id_solicitud`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_hes_estado`
    FOREIGN KEY (`id_estado`)
    REFERENCES `labficat`.`estado_solicitud` (`id_estado`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_hes_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `labficat`.`usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`cotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`cotizacion` (
  `id_cotizacion` INT NOT NULL AUTO_INCREMENT,
  `id_solicitud` INT NOT NULL,
  `valor_total` DECIMAL(11,2) NOT NULL DEFAULT 0,
  `estado` ENUM('PENDIENTE', 'ACEPTADA', 'RECHAZADA') NOT NULL DEFAULT 'PENDIENTE',
  `fecha_emision` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_decision` DATETIME NULL DEFAULT NULL,
  `motivo_rechazo` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cotizacion`),
  INDEX `idx_cotizacion_solicitud` (`id_solicitud` ASC) VISIBLE,
  CONSTRAINT `fk_cotizacion_solicitud`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `labficat`.`solicitud` (`id_solicitud`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`cotizacion_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`cotizacion_detalle` (
  `id_cotizacion` INT NOT NULL,
  `id_analisis` INT NOT NULL,
  `tarifa_aplicada` DECIMAL(11,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_cotizacion`, `id_analisis`),
  INDEX `idx_cotizacion_detalle_analisis` (`id_analisis` ASC) VISIBLE,
  CONSTRAINT `fk_cotizacion_detalle_cotizacion`
    FOREIGN KEY (`id_cotizacion`)
    REFERENCES `labficat`.`cotizacion` (`id_cotizacion`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_cotizacion_detalle_analisis`
    FOREIGN KEY (`id_analisis`)
    REFERENCES `labficat`.`analisis` (`id_analisis`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`cupon_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`cupon_pago` (
  `id_cupon` INT NOT NULL AUTO_INCREMENT,
  `id_cotizacion` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `codigo_cupon` VARCHAR(45) NULL DEFAULT NULL,
  `valor` DECIMAL(11,2) NOT NULL,
  `estado` ENUM('PENDIENTE', 'GENERADO', 'UTILIZADO', 'VENCIDO') NOT NULL DEFAULT 'PENDIENTE',
  `fecha_solicitud` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_generacion` DATETIME NULL DEFAULT NULL,
  `fecha_vencimiento` DATETIME GENERATED ALWAYS AS (IF(`fecha_generacion` IS NULL, NULL, `fecha_generacion` + INTERVAL 5 DAY)) STORED,
  PRIMARY KEY (`id_cupon`),
  UNIQUE INDEX `uq_cupon_codigo` (`codigo_cupon` ASC) VISIBLE,
  INDEX `idx_cupon_cotizacion` (`id_cotizacion` ASC) VISIBLE,
  INDEX `idx_cupon_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_cupon_cotizacion`
    FOREIGN KEY (`id_cotizacion`)
    REFERENCES `labficat`.`cotizacion` (`id_cotizacion`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_cupon_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `labficat`.`usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`recordatorio_cupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`recordatorio_cupon` (
  `id_recordatorio` INT NOT NULL AUTO_INCREMENT,
  `id_cupon` INT NOT NULL,
  `fecha_envio` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_recordatorio`),
  INDEX `idx_recordatorio_cupon` (`id_cupon` ASC) VISIBLE,
  CONSTRAINT `fk_recordatorio_cupon`
    FOREIGN KEY (`id_cupon`)
    REFERENCES `labficat`.`cupon_pago` (`id_cupon`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`soporte_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`soporte_pago` (
  `id_soporte` INT NOT NULL AUTO_INCREMENT,
  `id_cupon` INT NOT NULL,
  `id_validador` INT NULL DEFAULT NULL,
  `ruta_archivo` VARCHAR(255) NOT NULL,
  `formato` ENUM('PDF', 'JPG', 'PNG') NOT NULL,
  `estado` ENUM('PENDIENTE_VERIFICACION', 'APROBADO', 'RECHAZADO') NOT NULL DEFAULT 'PENDIENTE_VERIFICACION',
  `fecha_carga` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_validacion` DATETIME NULL DEFAULT NULL,
  `observaciones` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id_soporte`),
  INDEX `idx_soporte_cupon` (`id_cupon` ASC) VISIBLE,
  INDEX `idx_soporte_validador` (`id_validador` ASC) VISIBLE,
  CONSTRAINT `fk_soporte_cupon`
    FOREIGN KEY (`id_cupon`)
    REFERENCES `labficat`.`cupon_pago` (`id_cupon`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_soporte_validador`
    FOREIGN KEY (`id_validador`)
    REFERENCES `labficat`.`usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`muestra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`muestra` (
  `id_muestra` INT NOT NULL AUTO_INCREMENT,
  `id_solicitud` INT NOT NULL,
  `id_tipo_muestra` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `codigo_muestra` VARCHAR(13) NULL DEFAULT NULL,
  `fecha_asignacion_codigo` DATETIME NULL DEFAULT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `cantidad_recibida` DECIMAL(7,2) NOT NULL DEFAULT 300.00,
  `unidad_medida` ENUM('ml', 'gr') NOT NULL,
  `numero_envases` INT NOT NULL DEFAULT 1,
  `condiciones_conservacion` VARCHAR(200) NULL DEFAULT NULL,
  `estado_recepcion` ENUM('ACEPTADA', 'RECHAZADA') NOT NULL,
  `motivo_rechazo` VARCHAR(200) NULL DEFAULT NULL,
  `prioridad` INT NOT NULL DEFAULT 3,
  `fecha_recepcion` DATETIME NOT NULL,
  `observaciones` VARCHAR(200) NULL DEFAULT NULL,
  `id_solicitud_aceptada` INT GENERATED ALWAYS AS (IF(`estado_recepcion` = 'ACEPTADA', `id_solicitud`, NULL)) VIRTUAL,
  PRIMARY KEY (`id_muestra`),
  UNIQUE INDEX `uq_muestra_codigo` (`codigo_muestra` ASC) VISIBLE,
  UNIQUE INDEX `uq_muestra_solicitud_aceptada` (`id_solicitud_aceptada` ASC) VISIBLE,
  INDEX `idx_muestra_solicitud` (`id_solicitud` ASC) VISIBLE,
  INDEX `idx_muestra_tipo` (`id_tipo_muestra` ASC) VISIBLE,
  INDEX `idx_muestra_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `idx_muestra_cola` (`prioridad` ASC, `fecha_recepcion` ASC) VISIBLE,
  UNIQUE INDEX `numero_envases_UNIQUE` (`numero_envases` ASC) VISIBLE,
  CONSTRAINT `fk_muestra_solicitud`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `labficat`.`solicitud` (`id_solicitud`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_muestra_tipo`
    FOREIGN KEY (`id_tipo_muestra`)
    REFERENCES `labficat`.`tipo_muestra` (`id_tipo_muestra`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_muestra_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `labficat`.`usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`historial_prioridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`historial_prioridad` (
  `id_hist_prioridad` INT NOT NULL AUTO_INCREMENT,
  `id_muestra` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `nivel` INT NOT NULL,
  `motivo` VARCHAR(200) NOT NULL,
  `fecha_hora` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_hist_prioridad`),
  INDEX `idx_hist_prioridad_muestra` (`id_muestra` ASC) VISIBLE,
  INDEX `idx_hist_prioridad_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_hist_prioridad_muestra`
    FOREIGN KEY (`id_muestra`)
    REFERENCES `labficat`.`muestra` (`id_muestra`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_hist_prioridad_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `labficat`.`usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`rotulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`rotulo` (
  `id_rotulo` INT NOT NULL AUTO_INCREMENT,
  `id_muestra` INT NOT NULL,
  `fecha_generacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ruta_pdf` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_rotulo`),
  UNIQUE INDEX `uq_rotulo_muestra` (`id_muestra` ASC) VISIBLE,
  CONSTRAINT `fk_rotulo_muestra`
    FOREIGN KEY (`id_muestra`)
    REFERENCES `labficat`.`muestra` (`id_muestra`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`rotulo_parametro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`rotulo_parametro` (
  `id_rotulo` INT NOT NULL,
  `id_parametro` INT NOT NULL,
  PRIMARY KEY (`id_rotulo`, `id_parametro`),
  INDEX `idx_rotulo_parametro_parametro` (`id_parametro` ASC) VISIBLE,
  CONSTRAINT `fk_rotulo_parametro_rotulo`
    FOREIGN KEY (`id_rotulo`)
    REFERENCES `labficat`.`rotulo` (`id_rotulo`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_rotulo_parametro_parametro`
    FOREIGN KEY (`id_parametro`)
    REFERENCES `labficat`.`parametro` (`id_parametro`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`seguimiento_muestra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`seguimiento_muestra` (
  `id_seguimiento` BIGINT NOT NULL AUTO_INCREMENT,
  `id_muestra` INT NOT NULL,
  `id_etapa` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `fecha_hora` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `observaciones` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id_seguimiento`),
  INDEX `idx_seguimiento_muestra` (`id_muestra` ASC) VISIBLE,
  INDEX `idx_seguimiento_etapa` (`id_etapa` ASC) VISIBLE,
  INDEX `idx_seguimiento_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_seguimiento_muestra`
    FOREIGN KEY (`id_muestra`)
    REFERENCES `labficat`.`muestra` (`id_muestra`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_seguimiento_etapa`
    FOREIGN KEY (`id_etapa`)
    REFERENCES `labficat`.`etapa_proceso` (`id_etapa`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_seguimiento_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `labficat`.`usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`orden_analisis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`orden_analisis` (
  `id_orden` INT NOT NULL AUTO_INCREMENT,
  `id_muestra` INT NOT NULL,
  `id_analisis` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_orden_anterior` INT NULL DEFAULT NULL,
  `numero_iteracion` INT NOT NULL DEFAULT 1,
  `proceso` VARCHAR(250) NULL DEFAULT NULL,
  `estado` ENUM('PENDIENTE', 'EN_PROCESO', 'FINALIZADA', 'INVALIDADA') NOT NULL DEFAULT 'PENDIENTE',
  `fecha_inicio` DATETIME NULL DEFAULT NULL,
  `fecha_fin` DATETIME NULL DEFAULT NULL,
  `observaciones` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id_orden`),
  INDEX `idx_orden_muestra` (`id_muestra` ASC) VISIBLE,
  INDEX `idx_orden_analisis` (`id_analisis` ASC) VISIBLE,
  INDEX `idx_orden_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `idx_orden_anterior` (`id_orden_anterior` ASC) VISIBLE,
  CONSTRAINT `fk_orden_muestra`
    FOREIGN KEY (`id_muestra`)
    REFERENCES `labficat`.`muestra` (`id_muestra`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_orden_analisis`
    FOREIGN KEY (`id_analisis`)
    REFERENCES `labficat`.`analisis` (`id_analisis`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_orden_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `labficat`.`usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_orden_anterior`
    FOREIGN KEY (`id_orden_anterior`)
    REFERENCES `labficat`.`orden_analisis` (`id_orden`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`resultado_parametro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`resultado_parametro` (
  `id_orden` INT NOT NULL,
  `id_parametro` INT NOT NULL,
  `valor` DECIMAL(14,4) NULL DEFAULT NULL,
  PRIMARY KEY (`id_orden`, `id_parametro`),
  INDEX `idx_resultado_parametro` (`id_parametro` ASC) VISIBLE,
  CONSTRAINT `fk_resultado_orden`
    FOREIGN KEY (`id_orden`)
    REFERENCES `labficat`.`orden_analisis` (`id_orden`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_resultado_parametro`
    FOREIGN KEY (`id_parametro`)
    REFERENCES `labficat`.`parametro` (`id_parametro`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`validacion_resultado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`validacion_resultado` (
  `id_validacion` INT NOT NULL AUTO_INCREMENT,
  `id_orden` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `decision` ENUM('APROBADO', 'RECHAZADO') NOT NULL,
  `motivo` VARCHAR(500) NULL DEFAULT NULL,
  `fecha_hora` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_validacion`),
  INDEX `idx_validacion_orden` (`id_orden` ASC) VISIBLE,
  INDEX `idx_validacion_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_validacion_orden`
    FOREIGN KEY (`id_orden`)
    REFERENCES `labficat`.`orden_analisis` (`id_orden`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_validacion_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `labficat`.`usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`informe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`informe` (
  `id_informe` INT NOT NULL AUTO_INCREMENT,
  `id_muestra` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `ruta_pdf` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_generacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_envio` DATETIME NULL DEFAULT NULL,
  `fecha_descarga` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_informe`),
  UNIQUE INDEX `uq_informe_muestra` (`id_muestra` ASC) VISIBLE,
  INDEX `idx_informe_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_informe_muestra`
    FOREIGN KEY (`id_muestra`)
    REFERENCES `labficat`.`muestra` (`id_muestra`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_informe_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `labficat`.`usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`encuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`encuesta` (
  `id_encuesta` INT NOT NULL AUTO_INCREMENT,
  `id_solicitud` INT NOT NULL,
  `fecha_respuesta` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `satisfaccion_general` INT NOT NULL,
  `tiempo_entrega` INT NOT NULL,
  `atencion_personal` INT NOT NULL,
  `claridad_informe` INT NOT NULL,
  `recomendaria_servicio` TINYINT(1) NOT NULL,
  `comentarios` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id_encuesta`),
  UNIQUE INDEX `uq_encuesta_solicitud` (`id_solicitud` ASC) VISIBLE,
  CONSTRAINT `fk_encuesta_solicitud`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `labficat`.`solicitud` (`id_solicitud`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`reclamacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`reclamacion` (
  `id_reclamacion` INT NOT NULL AUTO_INCREMENT,
  `id_solicitud` INT NOT NULL,
  `codigo_soporte` VARCHAR(13) NOT NULL,
  `motivo` VARCHAR(500) NOT NULL,
  `estado` ENUM('ABIERTA', 'RESUELTA') NOT NULL DEFAULT 'ABIERTA',
  `fecha_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_resolucion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_reclamacion`),
  UNIQUE INDEX `uq_reclamacion_codigo` (`codigo_soporte` ASC) VISIBLE,
  INDEX `idx_reclamacion_solicitud` (`id_solicitud` ASC) VISIBLE,
  CONSTRAINT `fk_reclamacion_solicitud`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `labficat`.`solicitud` (`id_solicitud`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`evidencia_reclamacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`evidencia_reclamacion` (
  `id_evidencia` INT NOT NULL AUTO_INCREMENT,
  `id_reclamacion` INT NOT NULL,
  `ruta_archivo` VARCHAR(255) NOT NULL,
  `formato` ENUM('PNG', 'JPG', 'JPEG') NOT NULL,
  PRIMARY KEY (`id_evidencia`),
  INDEX `idx_evidencia_reclamacion` (`id_reclamacion` ASC) VISIBLE,
  CONSTRAINT `fk_evidencia_reclamacion`
    FOREIGN KEY (`id_reclamacion`)
    REFERENCES `labficat`.`reclamacion` (`id_reclamacion`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`table1` (
)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `labficat`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`permisos` (
  `id_permiso` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `modulos_permitidos` VARCHAR(45) NULL,
  PRIMARY KEY (`id_permiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labficat`.`rol_permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labficat`.`rol_permisos` (
  `permisos_id_permiso` INT NOT NULL,
  `rol_id_rol` INT NOT NULL,
  INDEX `fk_rol_permisos_permisos1_idx` (`permisos_id_permiso` ASC) VISIBLE,
  INDEX `fk_rol_permisos_rol1_idx` (`rol_id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_rol_permisos_permisos1`
    FOREIGN KEY (`permisos_id_permiso`)
    REFERENCES `labficat`.`permisos` (`id_permiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rol_permisos_rol1`
    FOREIGN KEY (`rol_id_rol`)
    REFERENCES `labficat`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `labficat`;

DELIMITER $$
USE `labficat`$$
CREATE TRIGGER `trg_muestra_codigo_automatico`
BEFORE INSERT ON `muestra`
FOR EACH ROW
BEGIN
  DECLARE v_anio CHAR(4);
  DECLARE v_seq  INT;

  IF NEW.`codigo_muestra` IS NULL AND NEW.`estado_recepcion` = 'ACEPTADA' THEN
    SET v_anio = DATE_FORMAT(IFNULL(NEW.`fecha_recepcion`, NOW()), '%Y');

    SELECT IFNULL(MAX(CAST(SUBSTRING_INDEX(`codigo_muestra`, '-', -1) AS UNSIGNED)), 0) + 1
      INTO v_seq
      FROM `muestra`
     WHERE `codigo_muestra` LIKE CONCAT('LAB-', v_anio, '-%');

    SET NEW.`codigo_muestra`          = CONCAT('LAB-', v_anio, '-', LPAD(v_seq, 4, '0'));
    SET NEW.`fecha_asignacion_codigo` = IFNULL(NEW.`fecha_asignacion_codigo`, NOW());
  END IF;
END$$

USE `labficat`$$
CREATE TRIGGER `trg_informe_requiere_encuesta`
BEFORE UPDATE ON `informe`
FOR EACH ROW
BEGIN
  IF NEW.`fecha_descarga` IS NOT NULL AND OLD.`fecha_descarga` IS NULL THEN
    IF NOT EXISTS (
      SELECT 1
        FROM `encuesta` e
        JOIN `muestra` m ON m.`id_solicitud` = e.`id_solicitud`
       WHERE m.`id_muestra` = NEW.`id_muestra`
    ) THEN
      SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Debe responder la encuesta de satisfaccion antes de descargar el informe';
    END IF;
  END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
